apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - argocd-repo-tools-secret.yaml
  - argocd-cluster-secret.yaml

patches:
  - path: argocd-server-patch.yaml
  - path: argocd-user-rbac.yaml
  - path: argocd-username-cm.yaml
  - path: argocd-pass-secret.yaml
