apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - path: argocd-server-patch.yaml
  - path: argocd-user-rbac.yaml
  - path: argocd-username-cm.yaml
  - path: argocd-pass-secret.yaml
