apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

resources:
  - jenkins-agent-rbac.yaml
  - jenkins-agent-sa.yaml
  - jenkins-go-agent.yaml
  - jenkins-jnlp.yaml
  - jenkins-react-agent.yaml
