apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

resources:
  - casc-jobdsl-seed-config.yaml
  - casc-jobdsl-go-config.yaml
  - casc-jobdsl-react-config.yaml
  - casc-jobdsl-project.yaml
