apiVersion: v1
kind: ConfigMap
metadata:
  name: casc-jobs-react-config
  namespace: jenkins
data:
   casc-jobs-react.yaml: |
    jobs:
      - script: |
          pipelineJob('reactjs-pipeline') {
            description('CI/CD Pipeline for React.js')
    
            definition {
              cps {
                sandbox(true)
                script("""
                  pipeline {
                    agent any
    
                    tools {
                      nodejs 'node18'
                    }
    
                    stages {
                      stage('Install & Build') {
                        steps {
                          sh 'npm install'
                          sh 'npm run build'
                        }
                      }
                    }
                  }
                """)
              }
            }
          }