apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

resources:
  - casc-jenkins-config.yaml
  - casc-jobs-seed.yaml
  - casc-tools-config.yaml
  - casc-credential.yaml
  - user-password.yaml
