apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

resources:
  - deployment.yaml
  - service-account.yaml
  - service.yaml
  - pvc-volume.yaml
  - plugin.yaml
  - jenkins-init-groovy.yaml
  - casc-jenkins-config.yaml
  - casc-jobs-go-config.yaml
  - casc-jobs-react-config.yaml
  - casc-tools-config.yaml
  - casc-jobdsl-go-config.yaml
  - casc-jobdsl-project.yaml
  - casc-jobdsl-react-config.yaml
  - casc-jobdsl-seed-config.yaml